apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  selector:
    app: portfolio
  ports:
    - protocol: TCP
      port: 80         # The port exposed by the service
      targetPort: 80   # The port inside the container where the app is running
      nodePort: 30001   # The port on each node to expose the service (you can choose any free port)
  type: NodePort
